### ISSUE TITLE
Add "how-to" about running the project locally.

### ISSUE THREAD

**Issue by bulhakovolexii** [Jakkkk136/Simulator_KHPI#2]
It would be nice to add brief instructions to README.md on how to run the project locally, so that it can be used without an Internet connection.

**Comment by Jakkkk136** [comment]
Hi bulhakovolexii,

Thank you for the suggestion! I've updated the README.md with instructions on how to run the project locally without an Internet connection. Please pull the latest changes and take a look. Let me know if everything is clear or if there are any other improvements you'd like to see.

Thanks for your contribution to the project!

Best regards,
Jakkkk136.

**Comment by bulhakovolexii** [comment]
### Great job! Thank you.❤️‍🔥

To popularize the project, I propose to prepare a joint article on the progress of development for the [Energy HUB](https://web.kpi.kharkov.ua/energyhub/) website.

Write to me at [t.me/behemothcat](https://t.me/behemothcat) when you are ready to share the story of the project's development.
